name: Release

on:
  push:
    branches:
      - next

defaults:
  run:
    shell: bash

jobs:
  snapshot-release:
    name: Create a snapshot release of a pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Bump Package Versions
        id: changesets
        run: |
          yarn changeset version --snapshot bulbasaur
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        id: publish
        run: |
          yarn changeset publish --tag bulbasaur --no-git-tag --snapshot
        env:
          # Needs access to publish to npm
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}